# '데이터 분석 NumPy 기초 문법 노트북'
> '2021년 여름 방학 데이터분석을 위한 NumPy 기초문법'

- toc:true
- branch: master
- badges: true
- comments: true
- author: leechaewon
- categories: [python, 데이터분석, numpy]

In [4]:
리스트 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
리스트[0][0]
리스트[2][0]
리스트*2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
import numpy as np

리스트 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
리스트 = np.array(리스트)
리스트*2
리스트 + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [7]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
a = np.arange(20).reshape(2, 2, 5)
a[0][1][2]

7

In [16]:
a = np.arange(15).reshape(3, 5)
a.shape # 행렬
a.ndim # 차원
a.dtype.name # 모르겠음..
a.itemsize
a.size # flat한(데이터를 일렬로 놓았을 때) 데이터 사이즈
type(a)


numpy.ndarray

In [17]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2, 3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [19]:
np.empty((2, 3))

array([[4.68961854e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [20]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [22]:
np.linspace(0, 9.5, 20) 

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [26]:
리스트 = [[10, 2, 3], [4, 5, 6], [7, 8, 9]]
a = np.array(리스트)
# a.sum(), sum(리스트) #sum(리스트)는 애러남
a.min(), min(리스트)
a.max(), max(리스트) #2개는 출력하는 결과도 다름

(10, [10, 2, 3])

In [27]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
b.sum(axis=0) # col기준으로 row끼리 더한 것 (세로)
b.sum(axis=1) # low기준으로 col끼리 더한 것 (가로)
b.sum() # flat하게 모두 더한 것

66

In [32]:
b.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
b.T #잘씀 둘이 같음
# b.transpose() #잘 안씀

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.floor([[5,6], [7, 8]])
np.vstack((a, b))
np.hstack((a, b))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [38]:
# 매우 잘씀
a = np.arange(12).reshape(3, 4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])